#### Correlation Analysis (task 3) on APPL

In [1]:
# Find the path

import os,sys
sys.path.append(os.path.abspath(os.path.join('..')))

from scripts.financial_analyzer import *

In [2]:
# read csv

News_df = pd.read_csv('../data/raw_analyst_ratings_data/raw_analyst_ratings.csv')
AAPL_df = load_data("../data/yfinance_data/AAPL_historical_data.csv")

In [3]:
# Apple dataset

AAPL_df

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098943,469033600,0.0,0.0
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093781,175884800,0.0,0.0
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086898,105728000,0.0,0.0
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089049,86441600,0.0,0.0
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.091630,73449600,0.0,0.0
...,...,...,...,...,...,...,...,...
2024-07-24,224.000000,224.800003,217.130005,218.539993,218.287323,61777600,0.0,0.0
2024-07-25,218.929993,220.850006,214.619995,217.490005,217.238556,51391200,0.0,0.0
2024-07-26,218.699997,219.490005,216.009995,217.960007,217.708008,41601300,0.0,0.0
2024-07-29,216.960007,219.300003,215.750000,218.240005,217.987686,36311800,0.0,0.0
2024-07-30,219.190002,220.330002,216.119995,218.800003,218.547043,41643800,0.0,0.0

In [4]:
# News on apple stock

AAPL_News =  News_df[News_df['stock'] == 'AAPL']
AAPL_News

,Unnamed: 0,headline,url,publisher,date,stock
6680,7120,Tech Stocks And FAANGS Strong Again To Start D...,https://www.benzinga.com/government/20/06/1622...,JJ Kinahan,2020-06-10 11:33:26-04:00,AAPL
6681,7121,10 Biggest Price Target Changes For Wednesday,https://www.benzinga.com/analyst-ratings/price...,Lisa Levin,2020-06-10 08:14:08-04:00,AAPL
6682,7122,"Benzinga Pro's Top 5 Stocks To Watch For Wed.,...",https://www.benzinga.com/short-sellers/20/06/1...,Benzinga Newsdesk,2020-06-10 07:53:47-04:00,AAPL
6683,7123,"Deutsche Bank Maintains Buy on Apple, Raises P...",https://www.benzinga.com/news/20/06/16219873/d...,Benzinga Newsdesk,2020-06-10 07:19:25-04:00,AAPL
6684,7124,Apple To Let Users Trade In Their Mac Computer...,https://www.benzinga.com/news/20/06/16218697/a...,Neer Varshney,2020-06-10 06:27:11-04:00,AAPL
...,...,...,...,...,...,...
7116,7585,"UBS Maintains Buy on Apple, Lowers Price Targe...",https://www.benzinga.com/news/20/03/15514989/u...,Vick Meyer,2020-03-10 00:00:00,AAPL
7117,7586,123 Biggest Movers From Yesterday,https://www.benzinga.com/news/20/03/15514298/1...,Lisa Levin,2020-03-10 00:00:00,AAPL
7118,7587,Crude Awakening: Energy Sector Takes A 20% Spi...,https://www.benzinga.com/news/earnings/20/03/1...,JJ Kinahan,2020-03-09 00:00:00,AAPL
7119,7588,Investor Movement Index Summary: February 2020,https://www.benzinga.com/news/earnings/20/03/1...,TD Ameritrade,2020-03-09 00:00:00,AAPL
7120,7589,101 Stocks Moving In Monday's Mid-Day Session,https://www.benzinga.com/news/20/03/15508983/1...,Lisa Levin,2020-03-09 00:00:00,AAPL

In [5]:
AAPL_df

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098943,469033600,0.0,0.0
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093781,175884800,0.0,0.0
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086898,105728000,0.0,0.0
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089049,86441600,0.0,0.0
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.091630,73449600,0.0,0.0
...,...,...,...,...,...,...,...,...
2024-07-24,224.000000,224.800003,217.130005,218.539993,218.287323,61777600,0.0,0.0
2024-07-25,218.929993,220.850006,214.619995,217.490005,217.238556,51391200,0.0,0.0
2024-07-26,218.699997,219.490005,216.009995,217.960007,217.708008,41601300,0.0,0.0
2024-07-29,216.960007,219.300003,215.750000,218.240005,217.987686,36311800,0.0,0.0
2024-07-30,219.190002,220.330002,216.119995,218.800003,218.547043,41643800,0.0,0.0

In [7]:
# Sentimental on apple news

AAPL_News = add_sentiment_score(News_df)

AAPL_News

,Unnamed: 0,headline,url,publisher,date,stock,Sentiment_Score,Sentiment_Category
6680,7120,Tech Stocks And FAANGS Strong Again To Start D...,https://www.benzinga.com/government/20/06/1622...,JJ Kinahan,2020-06-10 11:33:26-04:00,AAPL,0.433333,Positive
6681,7121,10 Biggest Price Target Changes For Wednesday,https://www.benzinga.com/analyst-ratings/price...,Lisa Levin,2020-06-10 08:14:08-04:00,AAPL,0.000000,Neutral
6682,7122,"Benzinga Pro's Top 5 Stocks To Watch For Wed.,...",https://www.benzinga.com/short-sellers/20/06/1...,Benzinga Newsdesk,2020-06-10 07:53:47-04:00,AAPL,0.500000,Positive
6683,7123,"Deutsche Bank Maintains Buy on Apple, Raises P...",https://www.benzinga.com/news/20/06/16219873/d...,Benzinga Newsdesk,2020-06-10 07:19:25-04:00,AAPL,0.000000,Neutral
6684,7124,Apple To Let Users Trade In Their Mac Computer...,https://www.benzinga.com/news/20/06/16218697/a...,Neer Varshney,2020-06-10 06:27:11-04:00,AAPL,0.000000,Neutral
...,...,...,...,...,...,...,...,...
7116,7585,"UBS Maintains Buy on Apple, Lowers Price Targe...",https://www.benzinga.com/news/20/03/15514989/u...,Vick Meyer,2020-03-10 00:00:00,AAPL,0.000000,Neutral
7117,7586,123 Biggest Movers From Yesterday,https://www.benzinga.com/news/20/03/15514298/1...,Lisa Levin,2020-03-10 00:00:00,AAPL,0.000000,Neutral
7118,7587,Crude Awakening: Energy Sector Takes A 20% Spi...,https://www.benzinga.com/news/earnings/20/03/1...,JJ Kinahan,2020-03-09 00:00:00,AAPL,-0.466667,Negative
7119,7588,Investor Movement Index Summary: February 2020,https://www.benzinga.com/news/earnings/20/03/1...,TD Ameritrade,2020-03-09 00:00:00,AAPL,0.000000,Neutral
7120,7589,101 Stocks Moving In Monday's Mid-Day Session,https://www.benzinga.com/news/20/03/15508983/1...,Lisa Levin,2020-03-09 00:00:00,AAPL,0.000000,Neutral

In [43]:
# Convert the data to datetime

AAPL_News['date'] = pd.to_datetime(AAPL_News['date'],utc=True)

# Reset index and rename the new column

# AAPL_df = AAPL_df.reset_index().rename(columns={'index': 'Date'})

In [44]:
AAPL_df

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Daily_Returns
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098943,469033600,0.0,0.0,NaN
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093781,175884800,0.0,0.0,-5.217061
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086898,105728000,0.0,0.0,-7.339788
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089049,86441600,0.0,0.0,2.475091
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.091630,73449600,0.0,0.0,2.899246
...,...,...,...,...,...,...,...,...,...,...
10993,2024-07-24,224.000000,224.800003,217.130005,218.539993,218.287323,61777600,0.0,0.0,-2.875428
10994,2024-07-25,218.929993,220.850006,214.619995,217.490005,217.238556,51391200,0.0,0.0,-0.480456
10995,2024-07-26,218.699997,219.490005,216.009995,217.960007,217.708008,41601300,0.0,0.0,0.216102
10996,2024-07-29,216.960007,219.300003,215.750000,218.240005,217.987686,36311800,0.0,0.0,0.128463
10997,2024-07-30,219.190002,220.330002,216.119995,218.800003,218.547043,41643800,0.0,0.0,0.256597

In [37]:
# Calculate Stock Movements
# Compute daily percentage change in closing prices to represent stock movements

AAPL_df['Daily_Returns'] = AAPL_df['Close'].pct_change() * 100

In [49]:
# Correlation Analysis
# Aggregate sentiment scores if multiple articles appear on the same day

daily_sentiment = AAPL_News.groupby('date')['Sentiment_Score'].mean().reset_index()

daily_sentiment

                        date  Sentiment_Score
0  2020-03-09 00:00:00+00:00        -0.155556
1  2020-03-10 00:00:00+00:00         0.021708
2  2020-03-11 00:00:00+00:00         0.018624
3  2020-03-12 00:00:00+00:00        -0.083048
4  2020-03-13 00:00:00+00:00         0.069215
..                       ...              ...
83 2020-06-10 10:27:11+00:00         0.000000
84 2020-06-10 11:19:25+00:00         0.000000
85 2020-06-10 11:53:47+00:00         0.500000
86 2020-06-10 12:14:08+00:00         0.000000
87 2020-06-10 15:33:26+00:00         0.433333

[88 rows x 2 columns]

In [50]:
# Ensure both datasets have the same dates
merged_data = pd.concat([daily_sentiment, AAPL_df], axis=1)

In [51]:
merged_data

,date,Sentiment_Score,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Daily_Returns
0,2020-03-09 00:00:00+00:00,-0.155556,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098943,469033600,0.0,0.0,NaN
1,2020-03-10 00:00:00+00:00,0.021708,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093781,175884800,0.0,0.0,-5.217061
2,2020-03-11 00:00:00+00:00,0.018624,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086898,105728000,0.0,0.0,-7.339788
3,2020-03-12 00:00:00+00:00,-0.083048,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089049,86441600,0.0,0.0,2.475091
4,2020-03-13 00:00:00+00:00,0.069215,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.091630,73449600,0.0,0.0,2.899246
...,...,...,...,...,...,...,...,...,...,...,...,...
10993,NaT,NaN,2024-07-24,224.000000,224.800003,217.130005,218.539993,218.287323,61777600,0.0,0.0,-2.875428
10994,NaT,NaN,2024-07-25,218.929993,220.850006,214.619995,217.490005,217.238556,51391200,0.0,0.0,-0.480456
10995,NaT,NaN,2024-07-26,218.699997,219.490005,216.009995,217.960007,217.708008,41601300,0.0,0.0,0.216102
10996,NaT,NaN,2024-07-29,216.960007,219.300003,215.750000,218.240005,217.987686,36311800,0.0,0.0,0.128463
10997,NaT,NaN,2024-07-30,219.190002,220.330002,216.119995,218.800003,218.547043,41643800,0.0,0.0,0.256597

In [54]:
print(len(merged_data['Sentiment_Score']))
print(len(merged_data['Daily_Returns']))

10998
10998

In [58]:
# Remove invalid values from both arrays

# Check for NaN or infinite values in the arrays
nan_mask = np.isnan(merged_data['Sentiment_Score']) | np.isnan(merged_data['Daily_Returns'])
inf_mask = np.isinf(merged_data['Sentiment_Score']) | np.isinf(merged_data['Daily_Returns'])

# Combine NaN and infinite masks
invalid_mask = nan_mask | inf_mask

clean_sentiment = merged_data['Sentiment_Score'][~invalid_mask]
clean_returns = merged_data['Daily_Returns'][~invalid_mask]

In [59]:
correlation = merged_data['Sentiment_Score'].corr(merged_data['Daily_Returns'])

print(f"Correlation between sentiment and daily stock returns: {correlation}")

Correlation between sentiment and daily stock returns: 0.03136125857509351